tap "buo/cask-upgrade"
tap "cmacrae/formulae"
tap "domq/gdb"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "koekeishiya/formulae"

brew "bat"
brew "black"
brew "blueutil"
brew "ccls"
brew "clang-format"
brew "cppman"
brew "curl"
brew "fd"
brew "figlet"
brew "fzf"
brew "gcc"
brew "gh"
brew "git"
brew "glfw"
brew "glow"
brew "go"
brew "openjdk"
brew "google-java-format"
brew "googletest"
brew "jq"
brew "pkg-config"
brew "luajit", args: ["HEAD"]
brew "luarocks"
brew "mas"
brew "neofetch"
brew "tree-sitter"
brew "neovim"
brew "node"
brew "nvm"
brew "pandoc"
brew "perl"
brew "prettier"
brew "python@3.9"
brew "ripgrep"
brew "rust"
brew "rustup-init"
brew "starship"
brew "stylua"
brew "the_silver_searcher"
brew "tldr"
brew "tree"
brew "wget"
brew "xclip"
brew "zsh"
brew "zsh-syntax-highlighting"
brew "koekeishiya/formulae/skhd"
brew "koekeishiya/formulae/yabai"
cask "font-hack-nerd-font"
cask "julia"
cask "mactex"
cask "zoom"

mas "GoodNotes", id: 1444383602
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Xcode", id: 497799835
